export default {
  siteName: 'Portal3',
  currentUser: 'currentUser',
  section: 'section',
  success: 'success',
  error: 'error',
  human: 'human',
  conference: 'conference',
  business: 'business',
  upcoming: 'upcoming',
  previous: 'previous',
  annual: 'annual',
  socialLinks: {
    twitter: 'https://twitter.com/elite_resources',
    youtube: 'https://www.youtube.com/channel/UCQdmdXSNkSJoZOwimDxz61g',
    linkedin: 'https://www.linkedin.com/company/elite-resources-center',
    snapchat: 'https://www.snapchat.com/add/g_chcs',
    whatsapp: 'https://iwtsp.com/966566655007',
  },
  contactInfo: {
    mobile: '+966566655007',
    phone: '0112304705',
    email: 'pm@eliteresources.co',
  },
  eventsCount: {
    recent: 3,
    normal: 50,
  },
  coursesCount: {
    recent: 3,
    normal: 50,
  },
  offset: {
    p1: 10,
    n1: -10,
    n2: -100,
  },
  annualUpcomingYear: 'annual-upcoming-year',
  annualUpcomingSummaryEn: 'annual-upcoming-summary-en',
  annualUpcomingSummaryAr: 'annual-upcoming-summary-ar',
}
