export default {
  app: '/app',
  home: '/home',
  adminPotal: "https://eliteresources.co/admin/",
  admin: "/admin",
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
    forgotPass: '/auth/forgot-pass',
    resetPass: '/auth/reset-pass',
  },
  human: {
    main: '/human',
    myaccount: '/human/myaccount',
    client: '/human/client',
    aboutUs: '/human/about-us',
  },
  conference: {
    main: '/conference',
    previousEvents: '/conference/previous-events',
    upcomingEvents: '/conference/upcoming-events',
    eventPhotos: '/conference/event-photos',
    eventJoin: '/conference/event-join',
    register: 'register',
    contactUs: '/conference/contact-us',
    sponsorRequest: '/conference/sponsor-request',
    prevSponsors: '/conference/prev-sponsors',
    directorBoard: '/conference/director-board',
    aboutUs: '/conference/about-us',
    myaccount: '/conference/myaccount',
  },
  business: {
    main: '/business',
    annualUpcoming: '/business/annual-upcoming',
    mostUpcoming: '/business/most-upcoming',
    upcoming: '/business/upcoming',
    previous: '/business/previous',
    prevClients: '/business/prev-clients',
    courseDetails: '/business/course-details',
    courseJoin: '/business/course-join',
    contactUs: '/business/contact-us',
    directorBoard: '/business/director-board',
    aboutUs: '/business/about-us',
    myaccount: '/business/myaccount',
  },
};
