export default {
  app: '/app',
  home: '/home',
  human: {
    main: '/human',
    myaccount: '/human/myaccount',
  },
  auth: {
    signIn: '/auth/sign-in',
    signUp: '/auth/sign-up',
  },
  conference: {
    main: '/conference',
    previousEvents: '/conference/previous-events',
    upcomingEvents: '/conference/upcoming-events',
    eventJoin: '/conference/event-join',
    register: 'register',
    contactUs: '/conference/contact-us',
    sponsorRequest: '/conference/sponsor-request',
    prevSponsors: '/conference/prev-sponsors',
    directorBoard: '/conference/director-board',
    myaccount: '/conference/myaccount',
  },
  business: {
    main: '/business',
    annualUpcoming: '/business/annual-upcoming',
    mostUpcoming: '/business/most-upcoming',
    upcoming: '/business/upcoming',
    previous: '/business/previous',
    courseDetails: '/business/course-details',
    courseJoin: '/business/course-join',
    contactUs: '/business/contact-us',
    directorBoard: '/business/director-board',
    myaccount: '/business/myaccount',
  },
};
